### ISSUE TITLE
[Feature Request] SVG Support

### ISSUE THREAD

**Issue by jlnrrg** [nineff/grayness#1]
Hello nineff,
your typst package worked very nice and helped me out a lot 😊.
Maybe you have an idea how support svg, too.
(maybe there exists a wasm functionality for svg to png conversion 😅)
For now I decided to just convert all my svgs to pngs to make them work with your package.

If this is out of scope, feel free to close this feature request.
Thanks a lot

**Comment by nineff** [comment]
SVG would work totally different, but should be doable, maybe even in Typst directly. (See [here](https://typst.app/docs/reference/visualize/image/#definitions-decode) for an example tho change colors)
I'll try to look into it, but cant promise any action soon.

**Comment by nineff** [comment]
I've updated the WASM Plugin, it now contains a new function `svg_grayscale`. You can use it as follows:

```typst
#let plg2= plugin("grayness.wasm")
#let svgbytes = plg.svg_grayscale(read("YourFile.svg", encoding: none))
#image.decode(svgbytes, format: "svg") 
```
I'll try to provide an Update for the package on Typst Universe as well.

**Comment by nineff** [comment]
[Example in the Typst WebApp](https://typst.app/project/rmRdbDptVvPL0O34xiU1G9)
